# SPDX-FileCopyrightText: 2026 The OSverflow Project
# SPDX-License-Identifier: Apache-2.0

LYRIQ_LOCAL_PREBUILTS := device/motorola/lyriq/.local-prebuilts
LYRIQ_LOCAL_SIGNING := device/motorola/lyriq/.local-signing

BOARD_PREBUILT_BOOTIMAGE := $(LYRIQ_LOCAL_PREBUILTS)/boot.img
BOARD_PREBUILT_BOOTIMAGE_PRESERVE_PAYLOAD := true
BOARD_PREBUILT_VENDOR_BOOTIMAGE := $(LYRIQ_LOCAL_PREBUILTS)/vendor_boot.img
BOARD_PREBUILT_VENDOR_BOOTIMAGE_PRESERVE_AVB_FOOTER := true
BOARD_PREBUILT_DTBOIMAGE := $(LYRIQ_LOCAL_PREBUILTS)/dtbo.img
BOARD_PREBUILT_VENDORIMAGE := $(LYRIQ_LOCAL_PREBUILTS)/vendor.img
BOARD_PREBUILT_VENDOR_DLKMIMAGE := $(LYRIQ_LOCAL_PREBUILTS)/vendor_dlkm.img
BOARD_PREBUILT_SYSTEM_DLKMIMAGE := $(LYRIQ_LOCAL_PREBUILTS)/system_dlkm.img

LYRIQ_AVB_KEY := $(LYRIQ_LOCAL_SIGNING)/lyriq-avb.pem
BOARD_AVB_KEY_PATH := $(LYRIQ_AVB_KEY)
BOARD_AVB_ALGORITHM := SHA256_RSA4096
BOARD_AVB_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --prop HAB_META:lyriq_50

BOARD_AVB_VBMETA_SYSTEM := system system_ext product
BOARD_AVB_VBMETA_SYSTEM_KEY_PATH := $(LYRIQ_AVB_KEY)
BOARD_AVB_VBMETA_SYSTEM_ALGORITHM := SHA256_RSA4096
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_AVB_VBMETA_SYSTEM_ROLLBACK_INDEX_LOCATION := 2
BOARD_AVB_MAKE_VBMETA_SYSTEM_IMAGE_ARGS += --prop HAB_META:lyriq_50
